name: ubuntu

on:
  push:
    tags:
      - "v*"
  pull_request:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-20.04
    if: github.repository == 'hzqst/metamod-fallguys'
    
    steps:
      - uses: hzqst/checkout@v2.3.4
      
      - name: Install build environment
        run: sudo apt-get install make build-essential gcc gcc-multilib g++-multilib
      
      - name: Build all
        run: |
          sudo chmod +777 build-all-linux.sh
          ./build-all-linux.sh
          
      - name: Remove placeholder
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: rm -f build/addons/metamod/dlls/.placeholder

      - name: Archive the build directory 
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'metamod-fallguys-ubuntu-i386.zip'
          path: 'build'
          exclusions: '.placeholder'
    
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: metamod-fallguys-${{ github.ref }}
          files: |
            metamod-fallguys-ubuntu-i386.zip